###
GET http://localhost:8082/phones
###
GET http://localhost:8082/users
###
POST http://localhost:8082/phones
content-type: application/json

{
    "name": "Dart Vader",
    "phone_number": "1",
    "owner": "6462ddca672921f355a64a28"
}
###
POST http://localhost:8083/users/
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "jonh1@gmail.com",
    "password": "12345678",
    "createdAt": "01/01/1900",
    "updatedAt": "01/01/1900",
    "thumbnail": "1.png"
}

###
PUT http://localhost:8082/users/6462ddca672921f355a64a28
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "jonh@asdas.com",
    "password": "12345678"
}

###
PUT http://localhost:8082/phones/6462ddd9672921f355a64a2a
content-type: application/json

{
   "phone_number": "1234567890"
}
###
DELETE http://localhost:8082/users/6462e0b632a1e0bd84f0412a

###
DELETE http://localhost:8082/phones/6462ddd9672921f355a64a2a

// Production

###
GET https://week6-zrfg.onrender.com/phones
###
GET https://week6-zrfg.onrender.com/users
###
POST https://week6-zrfg.onrender.com/phones
content-type: application/json

{
    "name": "Dart Vader",
    "phone_number": "111111111",
    "owner": "646d62ae2c185db2abaa930d"
}
###
POST https://week6-zrfg.onrender.com/users/
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "jonh1234@gmail.com",
    "password": "123456789",
    "createdAt": "01/01/1900",
    "updatedAt": "01/01/1900",
    "thumbnail": "1.png"
}

###
PUT https://week6-zrfg.onrender.com/users/646d6fc12db41b58eab02f9b
content-type: application/json

{
    "firstName": "R2D2",
    "lastName": "Kenobi",
    "email": "jonh123789@gmail.com",
    "password": "123456789"
}

###
PUT https://week6-zrfg.onrender.com/phones/6462ddd9672921f355a64a2a
content-type: application/json

{
   "phone_number": "1234567890"
}
###
DELETE https://week6-zrfg.onrender.com/users/646d6fc12db41b58eab02f9b

###
DELETE https://week6-zrfg.onrender.com/phones/6462ddd9672921f355a64a2a







