/* eslint-disable */

const swaggerAutogen = require('swagger-autogen')();

const doc = {
  info: {
    title: 'Phones API',
    description: 'Phones API for CES341 -  Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  consumes: ['application/json'],
  produces: ['application/json'],
  host: 'localhost:8082',
  schemes: ['http'],
};

const outputFile = './swagger-output.json';
const endpointsFiles = [
  './dist/src/api/phones.api.js',
  './dist/src/api/users.api.js',
  './dist/src/controllers/phones.controller.js',
  './dist/src/controllers/users.controller.js',
];

swaggerAutogen(outputFile, endpointsFiles, doc);
